### ISSUE TITLE
教程中提示的QSDK的Kernel和rootfs镜像，是否是从固件itb文件中分离出来的？

### ISSUE THREAD

**Issue by ghost65590** [0x5826/QNAP-QHora-301w-Guide#3]
我从**openwrt-ipq807x-generic-qnap_301w-initramfs-fit-uImage.itb**中只看到有**Kernel-1**和**fdt-1**镜像。还请扫盲介绍一下**rootfs**需要从哪里得到，万分感谢。
![6KJ@A1))JCGZJQV~QOT)TFF](https://user-images.githubusercontent.com/8151553/185441577-7606be90-36a6-481c-95f8-89bb04094387.png)
难道是刷openwrt-ipq807x-generic-qnap_301w-squashfs-factory.bin？抱歉提出这么肤浅的问题，确实有点懵。

**Comment by 0x5826** [comment]
就不是从这个文件里获取的，rootfs和kernel时从lean的qsdk的sysupgrade固件里解压得到的

**Comment by ghost65590** [comment]
非常感谢，已经顺利解出kernel和root包。越殂代疱补充如下：
**从sysupgrade.bin解包提取kernel和root的方法**

1、Ubuntu环境下安装binwalk和squashfs-tool包
```
sudo apt install binwalk
sudo apt install squashfs-tools
```

2、创建一个独立的文件夹并将sysupgrade.bin文件复制到该文件夹内，然后执行命令解压
```
binwalk -e openwrt-ipq807x-generic-qnap_301w-squashfs-sysupgrade.bin
```

3、执行命令成功后会自动生成一个文件以_.extracted_为结尾的文件夹。cd进入该文件夹并运行以下命令
```
unsquashfs -dest what-in-bin *.squashfs
```

4、完成后在以_.extracted_结尾的文件夹下，会生成一个_sysupgrade-qnap_301w_文件夹。内有所须的文件。
