### ISSUE TITLE
刷完kernel和rootfs重启后，貌似进入openwrt，但dhcp无法自动分配IP，也不知道默认网关IP，又来叨扰。

### ISSUE THREAD

**Issue by ghost65590** [0x5826/QNAP-QHora-301w-Guide#5]
手工设置客户端IP为192.168.100、192.168.1、192.168.10网段ip，分别访问100.1、1.1、10.1都不通，ssh也连不上，又卡壳了，
下的固件是[https://github.com/XXKDB/MI-R4A-breed-openwrt/releases/tag/2022.08.18-1323](url)的，哪也没找到默认IP是多少。
向继续求助，默认openwrt的网关ip是多少？

**Comment by 0x5826** [comment]
此固件非qsdk固件，我没有义务和能力解答
